version: '3'

services:
  reverse-proxy:
    image: traefik
    command:
      - --api.insecure=true
      - --providers.docker
      - --accesslog=true
      - --accesslog.filepath=/var/log/traefik/access.log
      - --log.level=DEBUG
      - --entrypoints.web.address=:80
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

    networks:
      - demo_net

  userdb:
    image: mysql
    container_name: user_db
    restart: always
    environment:
      MYSQL_DATABASE: 'city-db'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "3307:3306"
    networks:
      - demo_net

  user_management:
    image: user-management
    depends_on:
      - userdb
    deploy:
      replicas: 2
    environment:
      - DM_IP=device.localhost
      - DB_IP=userdb
      - DB_PORT=3306
      - DB_DBNAME=city-db
      - DB_USER=root
      - DB_PASSWORD=root
    networks:
      - demo_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.user_management.rule=Host(`user.localhost`)"
      - "traefik.http.services.user_management.loadbalancer.server.port=8080"

networks:
  demo_net:
    driver: bridge
    external: true
