version: '3.8'

services:
  chat-service:
    image: chat-management
    container_name: chat_management
    ports:
      - "8089:8089"
    networks:
      - demo_net

networks:
  demo_net:
    driver: bridge
    external: true
